# Dockerfile

# jdk17 Image Start
FROM openjdk:17
ARG DB_HOST
ARG DB_PORT
ARG DB_NAME
ARG DB_USER_NAME
ARG DB_PASSWORD
ARG JWT_SECRET
ARG FCM_APP_URL
ARG S3_BUCKET_NAME
ARG S3_ACCESS_KEY
ARG S3_SECRET_KEY
ARG DYNAMODB_ENDPOINT
ARG DYNAMODB_REGION
ARG DYNAMODB_ACCESS_KEY
ARG DYNAMODB_SECRET_KEY
ARG S3_URL

ENV DB_HOST=${DB_HOST} \
    DB_PORT=${DB_PORT} \
    DB_NAME=${DB_NAME} \
    DB_USER_NAME=${DB_USER_NAME} \
    DB_PASSWORD=${DB_PASSWORD} \
    JWT_SECRET=${JWT_SECRET} \
    FCM_APP_URL=${FCM_APP_URL} \
    S3_BUCKET_NAME=${S3_BUCKET_NAME} \
    S3_ACCESS_KEY=${S3_ACCESS_KEY} \
    S3_SECRET_KEY=${S3_SECRET_KEY} \
    DYNAMODB_ENDPOINT=${DYNAMODB_ENDPOINT} \
    DYNAMODB_REGION=${DYNAMODB_REGION} \
    DYNAMODB_ACCESS_KEY=${DYNAMODB_ACCESS_KEY} \
    DYNAMODB_SECRET_KEY=${DYNAMODB_SECRET_KEY} \
    S3_URL=${S3_URL}


# 인자 설정 - JAR_File
ARG JAR_FILE=build/libs/*.jar

# jar 파일 복제
COPY ${JAR_FILE} app.jar

# 인자 설정 부분과 jar 파일 복제 부분 합쳐서 진행해도 무방
#COPY build/libs/*.jar app.jar

# 실행 명령어
ENTRYPOINT ["java", "-jar", "app.jar"]