package sejongZoo.sejongZoo.faq.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;

import java.util.Date;

@Getter
@Builder
@DynamoDBTable(tableName = "faq")
@AllArgsConstructor
@NoArgsConstructor
@Setter // Setters are used in aws-dynamodb-sdk
public class Faq {
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String title;

    @DynamoDBAttribute
    private String context;

    @DynamoDBRangeKey(attributeName = "created_at")
    @DynamoDBAttribute
    private Date createdAt;
}